<?php
function read($file) {
  $row = 1;
  $array = array();
  if (($handle = fopen($file, "r")) !== FALSE) {
    while (($data = fgetcsv($handle, 1000, ",")) !== FALSE) {
      if ($row != 1) {
        $num = count($data);
        $row++;
        array_push($array, $data);
      } else {
        $row++;
      }
    }

    fclose($handle);
  }
  return $array;
}

function create_params_user_post() {
  $date = time();
  return array(
    'post_title'    => $date,
    'post_content'  => '',
    'post_status'   => 'publish',
    'post_author'   => 2,
    'post_category' => array( 2 )
  );
}

function create_params_airport($row, $pid) {
  return array(
    'field_603e810dff7d6' => $row[0],
    'field_603e8120ff7d7' => $row[1],
    'field_603e8126ff7d8' => $row[2],
    'field_603e812bff7d9' => $row[3],
    'field_603e8133ff7da' => $row[4],
    'field_603e813eff7db' => $row[5],
    'field_603e8143ff7dc' => $row[6],
    'field_603e8150ff7dd' => $row[7],
    'field_603e8155ff7de' => $row[8],
    'field_603e8158ff7df' => $row[9]
  );
}

function create_post($params) {
  return wp_insert_post( $params );
}

if ( !defined('ABSPATH') ) {
	require_once('./../../../wp-load.php');
}

if ( ! function_exists( 'wp_handle_upload' ) ) {
  require_once( ABSPATH . 'wp-admin/includes/file.php' );
}

$uploadedfile = $_FILES['file'];
$overrides = array( 
  'test_form' => false,
  'unique_filename_callback' => 'custom_filename'
);

$movefile = wp_handle_upload($uploadedfile, $overrides);

if ( $movefile && !isset( $movefile['error'] ) ) {
  echo "File is valid, and was successfully uploaded.\n";

  $file = $movefile;
  $url = $movefile['url'];
  $rows = read($url);
  $params_post = create_params_user_post($airports);
  $post = create_post($params_post);

  $upload_id = wp_insert_attachment( array(
		'guid'           => $movefile['file'], 
		'post_mime_type' => $movefile['type'],
		'post_title'     => custom_filename(),
		'post_content'   => '',
		'post_status'    => 'inherit'
	), $url );
 
	require_once( ABSPATH . 'wp-admin/includes/image.php' );
  require_once( ABSPATH . 'wp-admin/includes/post.php' );
	wp_update_attachment_metadata( $upload_id, wp_generate_attachment_metadata( $upload_id, $movefile['file'] ) );

  $moved = update_field('field_603e8911b1125', $upload_id, $post);

  wp_redirect( get_permalink($post), 302, 'post_creation' );
} else {
  /**
   * Error generated by _wp_handle_upload()
   * @see _wp_handle_upload() in wp-admin/includes/file.php
   */
  echo $movefile['error'];
}

?>